apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: nodejs-project
  namespace: argocd
spec:
  description: Node.js Application Project

  # Source repositories
  sourceRepos:
    - 'https://github.com/peterdangh/k8s-node-app'

  # Destination clusters and namespaces
  destinations:
    - namespace: default
      server: https://kubernetes.default.svc

  # Allowed Kubernetes resources
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: 'apps'
      kind: Deployment
    - group: 'networking.k8s.io'
      kind: Ingress

  namespaceResourceWhitelist:
    - group: ''
      kind: ConfigMap
    - group: ''
      kind: Service
    - group: 'apps'
      kind: Deployment
    - group: 'networking.k8s.io'
      kind: Ingress
